# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:D:/fjimenezga/Documents/H2/aa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    
# enable H2 web console and set url for web console
# http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /h2-console 

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    #database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO